import type { RelationshipType, BirthdayDesign } from '../types/birthday';

export interface RelationshipCategoryInfo {
  id: RelationshipType;
  type: RelationshipType;
  name: string;
  emoji: string;
  icon: string;
  tagline: string;
  description: string;
  badge: string;
  gradient: string;
}

export const ALL_RELATIONSHIPS: RelationshipCategoryInfo[] = [
  {
    id: 'girlfriend',
    type: 'girlfriend',
    name: 'Girlfriend / Lover',
    emoji: '❤️',
    icon: '❤️',
    tagline: 'Romantic & Emotional',
    description: 'Glowing hearts, love letters, floating rose petals, and intimate romantic surprises.',
    badge: 'Romantic Love Story',
    gradient: 'linear-gradient(135deg, #e11d48, #be123c, #881337)',
  },
  {
    id: 'parents',
    type: 'parents',
    name: 'Parents',
    emoji: '👨‍👩‍👦',
    icon: '👨‍👩‍👦',
    tagline: 'Warm & Deeply Grateful',
    description: 'Regal family crests, vintage photo albums, gratitude stories, and heartfelt family tributes.',
    badge: 'Heartfelt Family Tribute',
    gradient: 'linear-gradient(135deg, #78350f, #b45309, #d97706)',
  },
  {
    id: 'bestFriend',
    type: 'bestFriend',
    name: 'Best Friend',
    emoji: '🫂',
    icon: '🫂',
    tagline: 'Memes & Friendship Stats',
    description: 'Spotify-style recap wrapped, chaotic meme cards, WhatsApp chat stories, and adventure maps.',
    badge: 'Ultimate Friendship Mode',
    gradient: 'linear-gradient(135deg, #d97706, #e11d48, #7c3aed)',
  },
  {
    id: 'sibling',
    type: 'sibling',
    name: 'Brother / Sister',
    emoji: '👦',
    icon: '👦',
    tagline: 'Sibling Banter & Fights',
    description: 'Funny roast cards, childhood time machines, 8-bit retro arcade game mode, and sibling truces.',
    badge: 'Sibling Banter Edition',
    gradient: 'linear-gradient(135deg, #0284c7, #2563eb, #7c3aed)',
  },
  {
    id: 'collegeFriend',
    type: 'collegeFriend',
    name: 'College Friend',
    emoji: '🎓',
    icon: '🎓',
    tagline: 'Campus ID & Report Card',
    description: 'Interactive student ID badge, semester timelines, fake 0% attendance report cards, and yearbook memories.',
    badge: 'Campus Life Special',
    gradient: 'linear-gradient(135deg, #059669, #0d9488, #0284c7)',
  },
  {
    id: 'crush',
    type: 'crush',
    name: 'Crush',
    emoji: '💖',
    icon: '💖',
    tagline: 'Soft Lavender & Sweet Note',
    description: 'Ethereal pastel lavender, locked secret notes, little things admired, and starry skies.',
    badge: 'Sweet & Subtle Romance',
    gradient: 'linear-gradient(135deg, #a855f7, #ec4899, #f43f5e)',
  },
  {
    id: 'teacher',
    type: 'teacher',
    name: 'Teacher / Mentor',
    emoji: '👨‍🏫',
    icon: '👨‍🏫',
    tagline: 'Royal Navy & Lessons',
    description: 'Academic gold crests, vintage blackboard chalkboard aesthetic, life lessons, and digital thank-you books.',
    badge: 'Academic Tribute',
    gradient: 'linear-gradient(135deg, #1e3a8a, #1e40af, #b45309)',
  },
  {
    id: 'specialPerson',
    type: 'specialPerson',
    name: 'Special Person',
    emoji: '✨',
    icon: '✨',
    tagline: 'Cinematic Mystery & Stars',
    description: 'Mystery countdown reveals, planetary orbits, luxury golden cinema, and 3D surprise boxes.',
    badge: 'Mystery & Stardust',
    gradient: 'linear-gradient(135deg, #0f172a, #312e81, #701a75)',
  },
];

export const DESIGNS_BY_RELATIONSHIP: Record<RelationshipType, BirthdayDesign[]> = {
  girlfriend: [
    {
      id: 'romantic-rose',
      relationship: 'girlfriend',
      name: 'Romantic Rose',
      subtitle: 'Deep Red, Glowing Hearts & Floating Petals',
      description: 'Large couple photo in an animated glowing heart frame, "Why I Love You" interactive cards, love letter, and heart explosion finale.',
      theme_id: 'rose-romance',
      badge: 'Classic Romance',
      tags: ['Romantic', 'Heart Frame', 'Love Letter', 'Petals'],
      gradient: 'linear-gradient(135deg, #e11d48, #be123c, #881337)',
      previewImage: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Animated Glowing Heart Frame',
      timelineStyle: 'Rose Petal Path Timeline',
      finaleStyle: 'Heart Explosion Burst',
      features: ['10 Reasons Why I Love You Cards', 'Real-time Typewriter Love Letter', 'Heart Confetti Blast'],
    },
    {
      id: 'midnight-love',
      relationship: 'girlfriend',
      name: 'Midnight Love',
      subtitle: 'Starlit Sky, Glowing Moon & Cosmic Romance',
      description: 'Deep midnight indigo & neon violet aesthetic, glowing moon hero, "The Day I Met You", "Our Journey", and starry night sky constellation message.',
      theme_id: 'purple-galaxy',
      badge: 'Celestial Romance',
      tags: ['Midnight', 'Neon Pink', 'Moon & Stars', 'Cosmic'],
      gradient: 'linear-gradient(135deg, #0f172a, #581c87, #db2777)',
      previewImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Glowing Moon & Starry Constellation',
      timelineStyle: 'Starfield Milestone Trail',
      finaleStyle: 'Glowing Night Sky Starfall',
      features: ['"The Day I Met You" Card', '"Our Journey" Storyline', 'Constellation Glow Revealer'],
    },
    {
      id: 'polaroid-love',
      relationship: 'girlfriend',
      name: 'Polaroid Love',
      subtitle: 'Scrapbook Aesthetic, Washi Tape & Hand-Crafted Memories',
      description: 'Authentic Polaroid photo stacks with washi tape stickers, handwritten script notes, scrapbook timeline, and animated Polaroid heart collage.',
      theme_id: 'sakura-dream',
      badge: 'Scrapbook & Polaroids',
      tags: ['Polaroid', 'Washi Tape', 'Handwritten', 'Scrapbook'],
      gradient: 'linear-gradient(135deg, #fce7f3, #f472b6, #db2777)',
      previewImage: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Physical Polaroid Photo Stack with Tape',
      timelineStyle: 'Taped Polaroid Photo Album',
      finaleStyle: 'Heart-Shaped Polaroid Mosaic',
      features: ['Interactive Flippable Polaroids', 'Washi Tape Memory Cards', 'Heart Collage Mosaic'],
    },
    {
      id: 'cinematic-love',
      relationship: 'girlfriend',
      name: 'Cinematic Love',
      subtitle: 'Movie Poster Layout & Film Chapter Timeline',
      description: 'Hollywood film poster style hero, 35mm film reel photo layout, story broken into Chapters 01-04, and rolling cinematic movie credits finale.',
      theme_id: 'midnight-mystery',
      badge: 'Cinematic Movie',
      tags: ['Movie Poster', 'Film Reel', 'Chapters', 'Rolling Credits'],
      gradient: 'linear-gradient(135deg, #18181b, #27272a, #e11d48)',
      previewImage: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Wide Movie Poster Premiere Banner',
      timelineStyle: '35mm Film Reel Chapter Roadmap',
      finaleStyle: 'Rolling Movie Credits Birthday Tribute',
      features: ['Chapter 01-04 Film Sequence', 'Film Reel Photo Strip', 'Hollywood Movie Credits'],
    },
    {
      id: 'love-letter',
      relationship: 'girlfriend',
      name: 'Love Letter',
      subtitle: 'Animated Wax-Sealed Envelope & Diary Pages',
      description: 'Starts with an animated wax-sealed envelope ("Open My Letter ❤️"), unfolding into parchment diary pages with warm candle glow and handwritten finale.',
      theme_id: 'golden-luxury',
      badge: 'Unfolding Letter',
      tags: ['Wax Seal', 'Diary Pages', 'Parchment', 'Candlelight'],
      gradient: 'linear-gradient(135deg, #78350f, #b45309, #f59e0b)',
      previewImage: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Interactive Wax-Sealed Envelope Reveal',
      timelineStyle: 'Unfolding Diary Pages',
      finaleStyle: 'Handwritten Parchment Letter Spread',
      features: ['Click-to-Unfold Envelope', 'Interactive Diary Flip Pages', 'Warm Candle Glow Ambient'],
    },
  ],

  parents: [
    {
      id: 'family-legacy',
      relationship: 'parents',
      name: 'Family Legacy',
      subtitle: 'Cream & Gold Regal Family Tribute',
      description: 'Regal family crest, large family hero, tributes to "My First Heroes", "Your Sacrifices", and "Everything I am started with you".',
      theme_id: 'golden-luxury',
      badge: 'Regal Family Tribute',
      tags: ['Cream & Gold', 'First Heroes', 'Family Legacy', 'Gratitude'],
      gradient: 'linear-gradient(135deg, #78350f, #b45309, #d97706)',
      previewImage: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Regal Family Crest & Large Hero Portrait',
      timelineStyle: 'Generational Milestone Timeline',
      finaleStyle: 'Golden Family Light Burst',
      features: ['"My First Heroes" Tribute Card', '"Your Sacrifices" Gratitude Section', 'Golden Blessing Finale'],
    },
    {
      id: 'golden-memories',
      relationship: 'parents',
      name: 'Golden Memories',
      subtitle: 'Vintage Film Grain & Old Printed Photo Album',
      description: 'Sepia warmth, textured vintage photo frames, nostalgic retro timeline, and shimmering golden particle dust shower.',
      theme_id: 'golden-luxury',
      badge: 'Vintage Memories',
      tags: ['Vintage', 'Sepia', 'Film Grain', 'Old Photos'],
      gradient: 'linear-gradient(135deg, #451a03, #78350f, #b45309)',
      previewImage: 'https://images.unsplash.com/photo-1476703993599-0035a21b17a9?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Framed Vintage Sepia Portrait',
      timelineStyle: 'Old Printed Photo Album Flip',
      finaleStyle: 'Golden Particle Dust Shower',
      features: ['Vintage Film Grain Filter', 'Printed Border Photo Cards', 'Golden Dust Particle Finale'],
    },
    {
      id: 'home-heart',
      relationship: 'parents',
      name: 'Home & Heart',
      subtitle: 'Warm Cozy Home Atmosphere & Soft Hearth Glow',
      description: 'Cozy fireside ambiance, "Home isn\'t a place. It\'s you.", childhood roots, family recipes, and heartfelt thank-you gratitude note.',
      theme_id: 'sunset-bliss',
      badge: 'Cozy Home',
      tags: ['Home & Hearth', 'Warm Amber', 'Childhood', 'Family Hugs'],
      gradient: 'linear-gradient(135deg, #c2410c, #ea580c, #fb923c)',
      previewImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Cozy Fireside & Warm Hearth Tribute',
      timelineStyle: 'Childhood Home Memories Trail',
      finaleStyle: 'Glowing Sky Lantern Release',
      features: ['"Home Isn\'t A Place, It\'s You" Hero', 'Childhood Lessons Cards', 'Warm Hearth Amber Atmosphere'],
    },
    {
      id: 'gratitude-story',
      relationship: 'parents',
      name: 'Gratitude Story',
      subtitle: 'Minimal Editorial & Scroll-Revealed Sentences',
      description: 'High-end editorial typography where each scroll unfolds a meaningful sentence: "You taught me to walk...", "You taught me to dream...", "Thank you, Mom/Dad".',
      theme_id: 'emerald-garden',
      badge: 'Editorial Gratitude',
      tags: ['Editorial', 'Minimalist', 'Scroll Sentences', 'Pure Emotion'],
      gradient: 'linear-gradient(135deg, #064e3b, #047857, #10b981)',
      previewImage: 'https://images.unsplash.com/photo-1506869640319-fe1a24fd76dc?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Bold Editorial Typography Tribute',
      timelineStyle: 'Scroll-Revealed Statement Cards',
      finaleStyle: 'Minimalist Golden Typography Finale',
      features: ['Scroll-Triggered Sentence Unfolds', '"You Taught Me..." Statements', 'Editorial Minimalist Cards'],
    },
    {
      id: 'family-album',
      relationship: 'parents',
      name: 'Family Album',
      subtitle: '3D Physical Book with Page-Turn Animations',
      description: 'Interactive leatherbound family album where users turn physical pages featuring dated photos, handwritten memories, and personal notes.',
      theme_id: 'golden-luxury',
      badge: '3D Photo Album',
      tags: ['Book Flip', '3D Pages', 'Dated Memories', 'Leather Album'],
      gradient: 'linear-gradient(135deg, #292524, #44403c, #78716c)',
      previewImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Embossed Leatherbound Album Cover',
      timelineStyle: 'Interactive 3D Book Page Turns',
      finaleStyle: 'Open Album Spread & Family Blessings',
      features: ['Interactive 3D Page Flip Mechanics', 'Dated Memorabilia Notes', 'Full Album Spread Finale'],
    },
  ],

  bestFriend: [
    {
      id: 'chaos-mode',
      relationship: 'bestFriend',
      name: 'Chaos Mode',
      subtitle: 'Meme Cards, Bold Stickers & Pure Energy',
      description: 'Crazy stickers, meme reaction badges, inside jokes decoder, wildest photo collage, and unhinged emoji explosion.',
      theme_id: 'candy-pop',
      badge: 'Meme & Chaos',
      tags: ['Memes', 'Stickers', 'Inside Jokes', 'Emoji Blast'],
      gradient: 'linear-gradient(135deg, #ea580c, #db2777, #9333ea)',
      previewImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Streetwear Sticker-Bomb Hero',
      timelineStyle: 'Comic Strip Memory Timeline',
      finaleStyle: 'Emoji Explosion & Confetti Cannon',
      features: ['Inside Jokes Interactive Cards', 'Meme Reaction Badges', 'Unhinged Emoji Confetti Blast'],
    },
    {
      id: 'friendship-wrapped',
      relationship: 'bestFriend',
      name: 'Friendship Wrapped',
      subtitle: 'Spotify Wrapped Style Annual Recap Interface',
      description: 'Interactive annual recap cards with dynamic counters: 3,450+ Hours Together, 1,200 Laughs, 42 Late Night Calls, 0 Brain Cells Left.',
      theme_id: 'neon-cyberpunk',
      badge: 'Recap Wrapped',
      tags: ['Spotify Wrapped', 'Stats Counter', 'Recap Cards', 'Top Duo'],
      gradient: 'linear-gradient(135deg, #18181b, #047857, #10b981)',
      previewImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Top Duo #1 Wrapped Card Banner',
      timelineStyle: 'Story Slide Recap Progression',
      finaleStyle: 'Shareable Wrapped Summary Card',
      features: ['Dynamic Stat Number Tickers', 'Personality Trait Badges', 'Shareable "Wrapped" Summary'],
    },
    {
      id: 'chat-story',
      relationship: 'bestFriend',
      name: 'Chat Story',
      subtitle: 'Interactive Messaging App Interface',
      description: 'Designed like WhatsApp/iMessage with dynamic chat bubbles, photo attachments, voice note player simulator, and "Typing..." birthday reveal.',
      theme_id: 'ocean-dream',
      badge: 'Chat Messaging',
      tags: ['WhatsApp UI', 'Chat Bubbles', 'Voice Memos', 'Typing Indicator'],
      gradient: 'linear-gradient(135deg, #0f172a, #0369a1, #0284c7)',
      previewImage: 'https://images.unsplash.com/photo-1611746872915-64382b5c76da?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Smartphone Chat Window Header',
      timelineStyle: 'Sequential Messaging Chat Feed',
      finaleStyle: 'Live Text Message Pop & Balloon Stream',
      features: ['Interactive Chat Bubbles with Photos', 'Voice Note Audio Simulator', '"Typing..." Surprise Message'],
    },
    {
      id: 'adventure-map',
      relationship: 'bestFriend',
      name: 'Adventure Map',
      subtitle: 'Interactive Friendship Roadmap & Travel Pins',
      description: 'Stylized travel map with interactive pins marking key memory spots (Road Trips, Favorite Café, Secret Hangout), unlocking photos on tap.',
      theme_id: 'sunset-bliss',
      badge: 'Roadmap & Pins',
      tags: ['Map Pins', 'Road Trips', 'Coordinates', 'Next Adventure'],
      gradient: 'linear-gradient(135deg, #065f46, #0d9488, #0284c7)',
      previewImage: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Illustrated Adventure World Map',
      timelineStyle: 'GPS Route Memory Waypoints',
      finaleStyle: 'Spinning Compass & Gold Trophy Pin',
      features: ['Clickable Map Waypoint Pins', 'Travel Stamp Memory Cards', '"Next Adventure Loading..." Card'],
    },
    {
      id: 'photo-wall',
      relationship: 'bestFriend',
      name: 'Photo Wall',
      subtitle: 'Dynamic Interactive Masonry & Expanding Tiles',
      description: 'Full-screen interactive photo wall where pictures tilt, float, and expand smoothly into full memory cards on click.',
      theme_id: 'purple-galaxy',
      badge: 'Interactive Masonry',
      tags: ['Photo Grid', 'Tile Expansion', 'Candid Moments', 'Squad Reel'],
      gradient: 'linear-gradient(135deg, #3b0764, #6b21a8, #c026d3)',
      previewImage: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Floating Dynamic Masonry Wall',
      timelineStyle: 'Expanding Photo Tile Cards',
      finaleStyle: 'Dynamic Photo Wall Mosaic Flash',
      features: ['Expanding 3D Photo Tiles', 'Candid Squad Highlight Reel', 'Fullscreen Lightbox Zooms'],
    },
  ],

  sibling: [
    {
      id: 'sibling-roast',
      relationship: 'sibling',
      name: 'Sibling Roast',
      subtitle: 'Playful Banter, Debt Counters & Sibling Truce',
      description: 'Hilarious roast cards ("Most Annoying Moment", "Things You Still Owe Me", "Who Mom Likes More"), ending with a sweet sibling truce.',
      theme_id: 'candy-pop',
      badge: 'Roast & Banter',
      tags: ['Roast Cards', 'Debts Owed', 'Banter Buttons', 'Sibling Truce'],
      gradient: 'linear-gradient(135deg, #c2410c, #ea580c, #e11d48)',
      previewImage: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Warning Sirens & Sibling Rivalry Trophy',
      timelineStyle: 'Banter Timeline of Infamous Fights',
      finaleStyle: 'Official Signed Sibling Truce Contract',
      features: ['Interactive Sibling Banter Buttons', 'Things You Still Owe Me List', 'Official Sibling Truce Certificate'],
    },
    {
      id: 'childhood-time-machine',
      relationship: 'sibling',
      name: 'Childhood Time Machine',
      subtitle: 'Time Scrub Timeline: Childhood to Today',
      description: 'Interactive decade scrubber that steps through Childhood -> Primary School -> Teenage Years -> Adults, shifting photos as you scrub.',
      theme_id: 'sunset-bliss',
      badge: 'Time Machine',
      tags: ['Decade Slider', 'Childhood', 'School Days', 'Adults Now'],
      gradient: 'linear-gradient(135deg, #1e3a8a, #0284c7, #0d9488)',
      previewImage: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Retro Time Dial & Year Stepper',
      timelineStyle: 'Interactive Era Scrubber (Childhood to Now)',
      finaleStyle: 'Time Warp Chrono Light Burst',
      features: ['Interactive Era Scrubber Controls', 'Then vs. Now Side-by-Side Photos', 'Nostalgic Childhood Throwbacks'],
    },
    {
      id: 'game-mode',
      relationship: 'sibling',
      name: 'Game Mode',
      subtitle: '8-Bit Arcade / Video Game Level Progression',
      description: 'Retro pixel art aesthetic with Level 1: Childhood, Level 2: School Days, Level 3: Sibling Boss Fights, and Level Complete: Birthday EXP bonus!',
      theme_id: 'neon-cyberpunk',
      badge: '8-Bit Arcade',
      tags: ['Pixel Art', 'Level Up', 'XP Bar', 'Boss Fights'],
      gradient: 'linear-gradient(135deg, #09090b, #4c1d95, #06b6d4)',
      previewImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
      heroStyle: '8-Bit Arcade Level 1 Screen & Health Bar',
      timelineStyle: 'Video Game Quest Level Progression',
      finaleStyle: 'VICTORY ROYALE 8-Bit Fireworks',
      features: ['Interactive Level Clear Badges', 'Sibling XP & Achievement Trophies', 'Arcade Boss Fight Memory Cards'],
    },
    {
      id: 'sibling-scrapbook',
      relationship: 'sibling',
      name: 'Sibling Scrapbook',
      subtitle: 'Handmade Paper, Doodles & Tape Stickers',
      description: 'Doodled arrows, notebook paper, torn photos, silly scribbles, and handmade sticky notes celebrating growing up together.',
      theme_id: 'sakura-dream',
      badge: 'Handmade Scrapbook',
      tags: ['Doodles', 'Notebook Paper', 'Sticky Notes', 'Torn Photos'],
      gradient: 'linear-gradient(135deg, #fef3c7, #fde047, #ca8a04)',
      previewImage: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Torn Notebook Paper Scrapbook Cover',
      timelineStyle: 'Hand-Drawn Scrapbook Collage Pages',
      finaleStyle: 'Hand-Drawn Birthday Cake & Confetti',
      features: ['Doodled Sticky Note Cards', 'Torn Paper Frame Photos', 'Secret Nickname Badges'],
    },
    {
      id: 'forever-family',
      relationship: 'sibling',
      name: 'Forever Family',
      subtitle: 'Emotional Editorial & Lifelong Bond',
      description: 'Clean, touching aesthetic focused on the irreplaceable lifelong bond of siblings: "No matter how much we fight, you are still my person".',
      theme_id: 'rose-romance',
      badge: 'Lifelong Bond',
      tags: ['Emotional', 'Inseparable', 'Lifelong Bond', 'My Person'],
      gradient: 'linear-gradient(135deg, #881337, #be123c, #fb7185)',
      previewImage: 'https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Minimalist Sibling Silhouette & Quote',
      timelineStyle: 'Growing Up Side-by-Side Timeline',
      finaleStyle: 'Warm Golden Horizon & Heartfelt Hug',
      features: ['"You Are Still My Person" Tribute', 'Side-by-Side Growth Timeline', 'Heartfelt Sibling Promise'],
    },
  ],

  collegeFriend: [
    {
      id: 'college-id',
      relationship: 'collegeFriend',
      name: 'College ID Card',
      subtitle: 'Interactive Student ID Badge & Campus Lanyard',
      description: 'Starts with an interactive University Student ID badge that flips on click to reveal campus memories, canteen tales, and bunked lectures.',
      theme_id: 'emerald-garden',
      badge: 'Student ID Card',
      tags: ['Student ID', 'Lanyard Badge', 'Campus Life', 'Roll Number'],
      gradient: 'linear-gradient(135deg, #064e3b, #047857, #10b981)',
      previewImage: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Flippable Holographic Student ID Badge',
      timelineStyle: 'Campus Department Memory Pathway',
      finaleStyle: 'Official College Graduate Stamp & Confetti',
      features: ['Interactive Flippable Student ID Badge', 'Barcode & Roll Number Scanner', 'Canteen & Bunk Memory Cards'],
    },
    {
      id: 'semester-journey',
      relationship: 'collegeFriend',
      name: 'Semester Journey',
      subtitle: 'Semester-by-Semester Progression Timeline',
      description: 'Semester 1 (Freshers) -> Semester 2 (Surviving Finals) -> Semester 3 (Internship Panic) -> Semester 4 (Epic Fest) -> Final Year (Graduation).',
      theme_id: 'ocean-dream',
      badge: 'Semester Timeline',
      tags: ['Semester 1-8', 'Freshers to Finals', 'College Fest', 'Alumni'],
      gradient: 'linear-gradient(135deg, #0c4a6e, #0284c7, #38bdf8)',
      previewImage: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Academic Syllabus Roadmap Banner',
      timelineStyle: 'Semester-Wise Milestone Road',
      finaleStyle: 'Graduation Cap Toss & Degree Spread',
      features: ['Semester 1 to Final Year Progression', 'Exam All-Nighter Survival Badges', 'College Fest Throwback Reel'],
    },
    {
      id: 'attendance-zero',
      relationship: 'collegeFriend',
      name: 'Attendance 0%',
      subtitle: 'Funny Fake Report Card & CGPA of Chaos',
      description: 'Fake College Transcript with Attendance 32% (Low), Fun 99% (Distinction), Sleep 5% (Failing), Gossip 100% (Gold Medalist).',
      theme_id: 'candy-pop',
      badge: 'Fake Report Card',
      tags: ['Attendance 0%', 'Fake CGPA', 'Backbencher', 'Report Card'],
      gradient: 'linear-gradient(135deg, #7c2d12, #ea580c, #facc15)',
      previewImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Official Transcript of Backbenchers',
      timelineStyle: 'Attendance Hall of Fame / Shame',
      finaleStyle: 'Dean\'s List of Chaos Medal Ceremony',
      features: ['Interactive Fake GPA Calculator', 'Backbencher Achievement Trophies', 'Assignment Copypasta Badges'],
    },
    {
      id: 'campus-map',
      relationship: 'collegeFriend',
      name: 'Campus Map',
      subtitle: 'Interactive Campus Blueprint & Hotspots',
      description: 'Interactive college campus map: tap the Canteen for food fights, Library for sleeping, Main Gate for bunking, and Ground for fest memories.',
      theme_id: 'sunset-bliss',
      badge: 'Campus Blueprint',
      tags: ['Campus Map', 'Canteen', 'Library Naps', 'Main Gate Bunk'],
      gradient: 'linear-gradient(135deg, #134e4a, #0d9488, #2dd4bf)',
      previewImage: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Blueprint Campus Aerial Map',
      timelineStyle: 'Campus Hotspot Waypoint Trail',
      finaleStyle: 'Campus Landmark Pin Explosion',
      features: ['Clickable Campus Landmarks (Canteen, Library, Gate)', 'Hotspot Memory Unlocks', 'Campus Legend Certificate'],
    },
    {
      id: 'graduation-memories',
      relationship: 'collegeFriend',
      name: 'Graduation Memories',
      subtitle: 'Yearbook Spread & Cap Toss Ceremony',
      description: 'Yearbook layout with senior superlatives ("Most Likely To Fall Asleep In Class"), polaroid spreads, and animated cap toss finale: "College ends. Friendship doesn\'t".',
      theme_id: 'golden-luxury',
      badge: 'Yearbook Cap Toss',
      tags: ['Yearbook', 'Senior Superlatives', 'Cap Toss', 'Forever Alums'],
      gradient: 'linear-gradient(135deg, #18181b, #27272a, #f59e0b)',
      previewImage: 'https://images.unsplash.com/photo-1535982330050-f1c2fb79ff78?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Embossed Class Yearbook Cover',
      timelineStyle: 'Yearbook Superlative Spreads',
      finaleStyle: 'Golden Graduation Cap Toss Ceremony',
      features: ['Senior Superlative Badges', 'Classmate Testimonials', 'Animated Graduation Cap Toss'],
    },
  ],

  crush: [
    {
      id: 'soft-lavender',
      relationship: 'crush',
      name: 'Soft Lavender',
      subtitle: 'Pastel Lavender, Subtle Glow & Ethereal Whites',
      description: 'Gentle lavender gradient, subtle glowing hearts, delicate serif typography, and peaceful romantic ambient tone.',
      theme_id: 'lavender-mist',
      badge: 'Pastel Lavender',
      tags: ['Lavender', 'Pastel', 'Subtle Glow', 'Delicate Serif'],
      gradient: 'linear-gradient(135deg, #581c87, #9333ea, #c084fc)',
      previewImage: 'https://images.unsplash.com/photo-1528183429752-a97d0bf99b5a?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Soft Pastel Lavender Glowing Frame',
      timelineStyle: 'Lavender Petal Memory Trail',
      finaleStyle: 'Soft Floating Lavender Petals',
      features: ['Gentle Admiring Quote Cards', 'Subtle Pastel Heart Glow', 'Delicate Whisper Birthday Note'],
    },
    {
      id: 'secret-note',
      relationship: 'crush',
      name: 'Secret Note',
      subtitle: 'Locked Secret Message with Mystery Unlock',
      description: 'A mysterious locked stationery note with an interactive "Unlock Secret Message" button that reveals a thoughtful, genuine birthday confession.',
      theme_id: 'rose-romance',
      badge: 'Secret Letter',
      tags: ['Secret Note', 'Locked Letter', 'Wax Seal', 'Confession'],
      gradient: 'linear-gradient(135deg, #831843, #be185d, #f472b6)',
      previewImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Sealed Envelope with Golden Keyhole',
      timelineStyle: 'Unfolding Secret Note Chapters',
      finaleStyle: 'Secret Unlocked Starburst Reveal',
      features: ['Interactive "Unlock Secret Message" Button', 'Delicate Envelope Unfolding Animation', 'Heartfelt Sweet Birthday Wish'],
    },
    {
      id: 'little-things',
      relationship: 'crush',
      name: 'Little Things',
      subtitle: 'Appreciating The Subtle Details',
      description: 'Dedicated cards highlighting: "Your Smile", "Your Kindness", "Your Voice", "Your Energy", and "Your Gentle Presence".',
      theme_id: 'sakura-dream',
      badge: 'Little Details',
      tags: ['Your Smile', 'Your Kindness', 'Your Energy', 'Subtle Admiration'],
      gradient: 'linear-gradient(135deg, #701a75, #a21caf, #e879f9)',
      previewImage: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Minimalist Card Deck of Admiration',
      timelineStyle: 'Subtle Details Appreciation Cards',
      finaleStyle: 'Shimmering Stardust Floating Particles',
      features: ['Cards for Smile, Voice, Kindness & Energy', 'Soft Card Hover Micro-Glow', 'Heartwarming Ending Compliment'],
    },
    {
      id: 'starry-crush',
      relationship: 'crush',
      name: 'Starry Crush',
      subtitle: 'Night Sky, Moon Phases & Constellations',
      description: 'Dark starry skies, shimmering constellations connecting photos, and gentle moonlit glow surrounding the birthday star.',
      theme_id: 'purple-galaxy',
      badge: 'Moonlit Stars',
      tags: ['Night Sky', 'Constellations', 'Moonlight', 'Shooting Stars'],
      gradient: 'linear-gradient(135deg, #0f172a, #312e81, #6366f1)',
      previewImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Celestial Moonlit Ring Hero',
      timelineStyle: 'Constellation Star Connecting Trail',
      finaleStyle: 'Falling Shooting Stars & Cosmic Wish',
      features: ['Interactive Star Constellation Lines', 'Glowing Moon Phase Hero', 'Shooting Star Birthday Finale'],
    },
    {
      id: 'minimal-white',
      relationship: 'crush',
      name: 'Minimal White',
      subtitle: 'Apple-Style Ultra-Clean Minimalist Editorial',
      description: 'Bold high-contrast black & white typography, generous breathing room, clean single photo spotlights, and restrained modern animations.',
      theme_id: 'golden-luxury',
      badge: 'Apple Minimalist',
      tags: ['Apple Style', 'High Contrast', 'Generous Whitespace', 'Modern'],
      gradient: 'linear-gradient(135deg, #18181b, #27272a, #52525b)',
      previewImage: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Ultra-Crisp Minimalist Typography Hero',
      timelineStyle: 'Full-Bleed Single Photo Spotlights',
      finaleStyle: 'Minimalist Monochrome Sparkle Burst',
      features: ['Ultra-Clean Large Serif Typography', 'Single Photo Focus Carousel', 'Understated Modern Luxury Feel'],
    },
  ],

  teacher: [
    {
      id: 'royal-mentor',
      relationship: 'teacher',
      name: 'Royal Mentor',
      subtitle: 'Deep Navy, Royal Gold & Academic Laurel Crest',
      description: 'Regal laurel wreath, formal academic styling, respectful gratitude tribute, and elegant gold seal.',
      theme_id: 'golden-luxury',
      badge: 'Academic Laurel',
      tags: ['Navy & Gold', 'Laurel Crest', 'Academic', 'Gratitude'],
      gradient: 'linear-gradient(135deg, #1e3a8a, #1e40af, #b45309)',
      previewImage: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Royal Laurel Crest & Tribute Plaque',
      timelineStyle: 'Academic Milestone Parchment',
      finaleStyle: 'Golden Ribbon & Crest Shower',
      features: ['Laurel Wreath Honorary Crest', 'Respectful Mentor Appreciation Letter', 'Golden Academic Seal'],
    },
    {
      id: 'classroom-memories',
      relationship: 'teacher',
      name: 'Classroom Memories',
      subtitle: 'Vintage Chalkboard & Handwritten Chalk Wisdom',
      description: 'Textured blackboard background, authentic white and gold chalk typography, chalkboard eraser wipes, and inspirational notes.',
      theme_id: 'midnight-mystery',
      badge: 'Chalkboard Slate',
      tags: ['Chalkboard', 'Chalk Typography', 'Classroom Wisdom', 'Notebook'],
      gradient: 'linear-gradient(135deg, #09090b, #18181b, #27272a)',
      previewImage: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Textured Classroom Blackboard Slate',
      timelineStyle: 'Chalk-Drawn Lesson Milestones',
      finaleStyle: 'Chalk Dust Sparkle & Gold Star Stamp',
      features: ['Realistic Chalkboard Texture', 'Handwritten Chalk Quotes', 'Gold Star Student Award'],
    },
    {
      id: 'lessons-for-life',
      relationship: 'teacher',
      name: 'Lessons For Life',
      subtitle: 'Numbered Wisdom Cards & Impact Timeline',
      description: 'Scroll-revealed numbered cards: Lesson 01: Integrity, Lesson 02: Curiosity, Lesson 03: Perseverance, Lesson 04: Courage.',
      theme_id: 'emerald-garden',
      badge: 'Wisdom Cards',
      tags: ['Lesson 01-04', 'Wisdom Cards', 'Guiding Light', 'Values'],
      gradient: 'linear-gradient(135deg, #064e3b, #047857, #0f766e)',
      previewImage: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Numbered Wisdom Hero Tribute',
      timelineStyle: 'Scroll-Revealed Lesson Plaques',
      finaleStyle: 'Golden Book of Knowledge Finale',
      features: ['Numbered Lesson Wisdom Plaques', 'Guiding Philosophy Quotes', 'Inspiring Legacy Tribute'],
    },
    {
      id: 'thank-you-book',
      relationship: 'teacher',
      name: 'Thank You Book',
      subtitle: 'Hardcover Embossed Digital Volume',
      description: 'Digital hardcover leather volume with gold leaf embossing, flipping open to show memories and thank-you notes from students.',
      theme_id: 'golden-luxury',
      badge: 'Hardcover Volume',
      tags: ['Embossed Book', 'Gold Leaf', 'Student Notes', 'Hardcover'],
      gradient: 'linear-gradient(135deg, #312e81, #1e1b4b, #b45309)',
      previewImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Embossed Gold Leaf Hardcover Book',
      timelineStyle: 'Flipping Book Chapter Spreads',
      finaleStyle: 'Gold Foil Leaf Burst & Certificate',
      features: ['3D Hardcover Book Spread', 'Student Testimonial Pages', 'Gold Leaf Embossed Seal'],
    },
    {
      id: 'academic-timeline',
      relationship: 'teacher',
      name: 'Academic Timeline',
      subtitle: 'Milestone Progression: First Lecture to Lifelong Inspiration',
      description: 'First Meeting -> First Great Lesson -> Personal Guidance -> Breakthrough Moment -> Lifelong Inspiration: "Thank you for shaping our future".',
      theme_id: 'ocean-dream',
      badge: 'Milestone Journey',
      tags: ['First Lecture', 'Mentorship', 'Breakthrough', 'Legacy'],
      gradient: 'linear-gradient(135deg, #0f172a, #1e3a8a, #0369a1)',
      previewImage: 'https://images.unsplash.com/photo-1532012164546-f432f2e3ddb5?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Academic Journey Roadmap Banner',
      timelineStyle: 'Chronological Mentorship Trail',
      finaleStyle: 'Royal Golden Shower & Standing Ovation',
      features: ['Mentorship Chronology Pathway', '"Breakthrough Moment" Spotlight', 'Honorary Mentor Plaque'],
    },
  ],

  specialPerson: [
    {
      id: 'mystery-reveal',
      relationship: 'specialPerson',
      name: 'Mystery Reveal',
      subtitle: 'Cinematic Blackout Countdown & Spotlight Reveal',
      description: 'Dramatic black background, suspenseful typewriter countdown ("Someone extraordinary was born today..."), and a grand spotlight unboxing.',
      theme_id: 'midnight-mystery',
      badge: 'Spotlight Reveal',
      tags: ['Blackout', 'Spotlight', 'Mystery Countdown', 'Epic Reveal'],
      gradient: 'linear-gradient(135deg, #09090b, #18181b, #4338ca)',
      previewImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Dramatic Spotlight & Mystery Countdown',
      timelineStyle: 'Unraveling Clues Timeline',
      finaleStyle: 'Cosmic Supernova & Fireworks',
      features: ['Suspenseful Mystery Countdown', 'Spotlight Beam Unboxing', 'Grand Dramatic Person Reveal'],
    },
    {
      id: 'galaxy-universe',
      relationship: 'specialPerson',
      name: 'Galaxy Universe',
      subtitle: 'Planetary Orbits, Nebulae & Cosmic Starfield',
      description: 'Interactive 3D orbit rings, photo enclosed in a swirling radiant star portal, floating space dust and constellation wish cards.',
      theme_id: 'purple-galaxy',
      badge: 'Cosmic Galaxy',
      tags: ['Orbit Rings', 'Nebula', 'Planetary', 'Cosmic Portal'],
      gradient: 'linear-gradient(135deg, #0f172a, #312e81, #701a75)',
      previewImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Radiant Galaxy Star Portal',
      timelineStyle: 'Planetary Orbit Trajectory',
      finaleStyle: 'Galactic Nebula Explosion',
      features: ['Interactive Planetary Orbit Rings', 'Glowing Celestial Star Portal', 'Stardust Nebula Particle Finale'],
    },
    {
      id: 'golden-cinematic',
      relationship: 'specialPerson',
      name: 'Golden Cinematic',
      subtitle: 'Black & Gold Luxury Film Premiere',
      description: 'High-end luxury serif, film grain, gold foil accents, cinematic aspect ratio photo reveals, and luxury premiere celebration.',
      theme_id: 'golden-luxury',
      badge: 'Luxury Cinema',
      tags: ['Gold & Black', 'Film Premiere', 'Luxury Serif', 'VIP Access'],
      gradient: 'linear-gradient(135deg, #09090b, #1c1917, #ca8a04)',
      previewImage: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Luxury Gold Film Premiere Title Card',
      timelineStyle: 'Scene-by-Scene Cinema Reel',
      finaleStyle: 'Golden Confetti & VIP Spotlight Finale',
      features: ['VIP Premiere Film Title Cards', 'Cinematic Widescreen Photo Reels', 'Luxury Gold Foil Typography'],
    },
    {
      id: 'memory-universe',
      relationship: 'specialPerson',
      name: 'Memory Universe',
      subtitle: 'Floating Interactive Planet Orbs',
      description: 'Memory cards rendered as floating planetary orbs with glowing rings. Tapping an orb expands it with smooth orbital physics.',
      theme_id: 'neon-cyberpunk',
      badge: 'Planet Orbs',
      tags: ['Floating Orbs', 'Planetary Rings', 'Orbital Physics', 'Constellation'],
      gradient: 'linear-gradient(135deg, #030712, #1e1b4b, #4c1d95)',
      previewImage: 'https://images.unsplash.com/photo-1507499739999-097706ad8914?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Interactive Planet Orb Cluster',
      timelineStyle: 'Floating Planet Memory Sphere Trail',
      finaleStyle: 'Cosmic Stardust Light Celebration',
      features: ['Click-to-Expand Planetary Orbs', 'Glowing Ring Physics', 'Orbital Stardust Aura'],
    },
    {
      id: 'surprise-box',
      relationship: 'specialPerson',
      name: 'Surprise Box',
      subtitle: 'Layered 3D Gift Box Unboxing',
      description: 'Starts with an animated golden mystery gift box. Tapping unlocks Layer 1 (Photo memories), Layer 2 (Secret wish cards), and Layer 3 (Grand finale message).',
      theme_id: 'sunset-bliss',
      badge: '3D Gift Box',
      tags: ['3D Gift Box', 'Multi-Layer', 'Unboxing', 'Grand Reveal'],
      gradient: 'linear-gradient(135deg, #831843, #c026d3, #7c3aed)',
      previewImage: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=800&q=80',
      heroStyle: 'Interactive 3D Ribbon Gift Box',
      timelineStyle: 'Layered Unboxing Stage Progression',
      finaleStyle: 'Multi-Stage Confetti & Sparkler Finale',
      features: ['3-Layer Interactive Unboxing Mechanics', 'Secret Surprise Cards', 'Grand Sparkler Explosion'],
    },
  ],
};

export const ALL_DESIGNS: BirthdayDesign[] = Object.values(DESIGNS_BY_RELATIONSHIP).flat();

export function getDesignsForRelationship(relationship: RelationshipType): BirthdayDesign[] {
  return DESIGNS_BY_RELATIONSHIP[relationship] || DESIGNS_BY_RELATIONSHIP.girlfriend;
}

export function getDefaultDesignForRelationship(relationship: RelationshipType): string {
  const designs = getDesignsForRelationship(relationship);
  return designs[0]?.id || 'romantic-rose';
}

export function getDesignById(designId?: string): BirthdayDesign {
  if (!designId) {
    return DESIGNS_BY_RELATIONSHIP.girlfriend[0];
  }
  const found = ALL_DESIGNS.find((d) => d.id === designId);
  return found || DESIGNS_BY_RELATIONSHIP.girlfriend[0];
}
